server:
  port: 10086
eureka:
  server:
    eviction-interval-timer-in-ms: 100000 #扫描失效服务间隔 毫秒
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka
    register-with-eureka: true  #是否要注册到其他eurekaServer
    fetch-registry: true #不需要从其他EurekaServer拉取注册信息
spring:
  application:
    name: eurekaServer
