server:
  port: 9004
spring:
  application:
    name: UserWeb04
  thymeleaf:
    cache: false
  cloud:
    loadbalancer:
      retry:
        enabled: true  #打开cloud的重试
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
USERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    OkToRetryOnAllOperations: false  #只针对读操作进行重试
      # Ribbon的连接超时时间
    ConnectTimeout: 250
      # Ribbon的数据读取超时时间
    ReadTimeout: 250
    MaxAutoRetriesNextServer: 1  #切换服务实例的次数
    MaxAutoRetries: 1
logging:
  level:
    com:
      offcn: debug
feign:
  hystrix:
    enabled: true
#设定Hystrix熔断超时时间 ，理论上熔断时间应该大于总连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
